from .models import db, MenuItem, MenuItemImg, environment, SCHEMA, add_prefix_for_prod
from sqlalchemy.sql import text
from random import randint, random
from faker import Faker

drink_translator={
"Cappuccino":f"/assets/menu_item_images/drinks/cappuccino/img_{randint(1, 5)}.jpeg",
"Gotham Red Wine": f"/assets/menu_item_images/drinks/gotham_red_wine/img_{randint(1, 5)}.jpeg",
"Margarita": f"/assets/menu_item_images/drinks/margarita/img_{randint(1, 5)}.jpeg",
"Redbull": f"/assets/menu_item_images/drinks/redbull/img_{randint(1, 5)}.jpeg",
"Seven and Seven":  f"/assets/menu_item_images/drinks/seven_and_seven/img_{randint(1, 5)}.jpeg",
"Sprite": f"/assets/menu_item_images/drinks/sprite/img_{randint(1, 5)}.jpeg",
"Gotham White Wine": f"/assets/menu_item_images/drinks/gotham_white_wine/img_{randint(1, 5)}.jpeg",
"Lemonade": f"/assets/menu_item_images/drinks/lemonade/img_{randint(1, 5)}.jpeg",
"Martini": f"/assets/menu_item_images/drinks/martini/img_{randint(1, 5)}.jpeg",
"Root Beer": f"/assets/menu_item_images/drinks/root_beer/img_{randint(1, 5)}.jpeg",
"Shirley Temple":  f"/assets/menu_item_images/drinks/shirley_temple/img_{randint(1, 5)}.jpeg",
"Coffee":  f"/assets/menu_item_images/drinks/Coffee/img_{randint(1, 5)}.jpeg",
"Gotham Beer": f"/assets/menu_item_images/drinks/gotham_beer/img_{randint(1, 5)}.jpeg",
"Long Island Iced Tea":  f"/assets/menu_item_images/drinks/long_island_iced_tea/img_{randint(1, 5)}.jpeg",
"Pepsi":  f"/assets/menu_item_images/drinks/pepsi/img_{randint(1, 5)}.jpeg",
"Rum and Coke":  f"/assets/menu_item_images/drinks/rum_and_coke/img_{randint(1, 5)}.jpeg",
"Smoothie":     f"/assets/menu_item_images/drinks/smoothie/img_{randint(1, 5)}.jpeg",
}
entree_translator= {
    "Buffalo Chicken Sandwich": f"/assets/menu_item_images/entrees/buffalo_chicken_sandwich/img_{randint(1, 5)}.jpeg",
    "Chicken Tenders": f"/assets/menu_item_images/entrees/chicken_tenders/img_{randint(1, 5)}.jpeg",
    "Lasagna": f"/assets/menu_item_images/entrees/lasagna/img_{randint(1, 5)}.jpeg",
    "Philly Cheesesteak": f"/assets/menu_item_images/entrees/philly_cheesesteak/img_{randint(1, 5)}.jpeg",
    "Spaghetti": f"/assets/menu_item_images/entrees/spaghetti/img_{randint(1, 5)}.jpeg",
    "Chicken Fajita": f"/assets/menu_item_images/entrees/chicken_fajita/img_{randint(1, 5)}.jpeg",
    "Fettuccine Alfredo": f"/assets/menu_item_images/entrees/fettuccine_alfredo/img_{randint(1, 5)}.jpeg",
    "Gyro": f"/assets/menu_item_images/entrees/gyro/img_{randint(1, 5)}.jpeg",
    "Lobster": f"/assets/menu_item_images/entrees/lobster/img_{randint(1, 5)}.jpeg",
    "Steak": f"/assets/menu_item_images/entrees/steak/img_{randint(1, 5)}.jpeg",
    "BBQ Ribs": f"/assets/menu_item_images/entrees/bbq_ribs/img_{randint(1, 5)}.jpeg",
    "Chicken Parm": f"/assets/menu_item_images/entrees/chicken_parmesean/img_{randint(1, 5)}.jpeg",
    "Fish & Chips": f"/assets/menu_item_images/entrees/fish_and_chips/img_{randint(1, 5)}.jpeg",
    "Hamburger": f"/assets/menu_item_images/entrees/hamburger/img_{randint(1, 5)}.jpeg",
    "Meatball Sandwich": f"/assets/menu_item_images/entrees/meatball_sandwich/img_{randint(1, 5)}.jpeg",
    "Shish Kebab": f"/assets/menu_item_images/entrees/shish_kebab/img_{randint(1, 5)}.jpeg",
    "Fish Tacos" : f"/assets/menu_item_images/entrees/fish_tacos/img_{randint(1, 5)}.jpeg",
    "Pizza" : f"/assets/menu_item_images/entrees/pizza/img_{randint(1, 5)}.jpeg"
}
dessert_translator= {
    'Blueberry tart': f"/assets/menu_item_images/desserts/blueberry_tart/img_{randint(1, 5)}.jpeg",
    "Chocolate Chip Cookie": f"/assets/menu_item_images/desserts/blueberry_tart/img_{randint(1, 5)}.jpeg",
    "Lava Cake": f"/assets/menu_item_images/desserts/lava_cake/img_{randint(1, 5)}.jpeg",
    "Pumpkin pie": f"/assets/menu_item_images/desserts/pumpkin_pie/img_{randint(1, 5)}.jpeg",
    'Carrot Cake': f"/assets/menu_item_images/desserts/carrot_cake/img_{randint(1, 5)}.jpeg",
    "Chocolate Mousse": f"/assets/menu_item_images/desserts/chocolate_mousse/img_{randint(1, 5)}.jpeg",
    "Milkshake": f"/assets/menu_item_images/desserts/milkshake/img_{randint(1, 5)}.jpeg",
    "Strawberry Shortcake": f"/assets/menu_item_images/desserts/strawberry_shortcake/img_{randint(1, 5)}.jpeg",
    'Apple Pie': f"/assets/menu_item_images/desserts/apple_pie/img_{randint(1, 5)}.jpeg",
    "Cheesecake": f"/assets/menu_item_images/desserts/cheesecake/img_{randint(1, 5)}.jpeg",
    "Cupcake": f"/assets/menu_item_images/desserts/cupcake/img_{randint(1, 5)}.jpeg",
    "Peach Cobbler": f"/assets/menu_item_images/desserts/peach_cobbler/img_{randint(1, 5)}.jpeg",
    "Tiramisu": f"/assets/menu_item_images/desserts/tiramisu/img_{randint(1, 5)}.jpeg",
    "Banana Split": f"/assets/menu_item_images/desserts/banana_split/img_{randint(1, 5)}.jpeg",
    "Chocolate Brownie": f"/assets/menu_item_images/desserts/chocolate_brownie/img_{randint(1, 5)}.jpeg",
    "Flan": f"/assets/menu_item_images/desserts/flan/img_{randint(1, 5)}.jpeg",
    "Pistachio Gelato": f"/assets/menu_item_images/desserts/pistachio_gelato/img_{randint(1, 5)}.jpeg",
    "Vanilla IceCream": f"/assets/menu_item_images/desserts/vanilla_icecream/img_{randint(1, 5)}.jpeg"
}
sides_translator= {
"Spaghetti": f"/assets/menu_item_images/sides/spaghetti/img_{randint(1, 5)}.jpeg",
"Chicken Wings": f"/assets/menu_item_images/sides/chicken_wings/img_{randint(1, 5)}.jpeg",
"Fried Rice": f"/assets/menu_item_images/sides/fried_rice/img_{randint(1, 5)}.jpeg",
"Green Beans": f"/assets/menu_item_images/sides/green_beans/img_{randint(1, 5)}.jpeg",
"Mozarella Sticks": f"/assets/menu_item_images/sides/mozarella_sticks/img_{randint(1, 5)}.jpeg",
"Roasted Veggies": f"/assets/menu_item_images/sides/roasted_veggies/img_{randint(1, 5)}.jpeg",
"Corn on the Cob": f"/assets/menu_item_images/sides/corn_on_the_cob/img_{randint(1, 5)}.jpeg",
"Fries": f"/assets/menu_item_images/sides/fries/img_{randint(1, 5)}.jpeg",
"Lo Mein": f"/assets/menu_item_images/sides/lo_mein/img_{randint(1, 5)}.jpeg",
"Nachos": f"/assets/menu_item_images/sides/nachos/img_{randint(1, 5)}.jpeg",
"Sweet Potato Fries": f"/assets/menu_item_images/sides/sweet_potato_fries/img_{randint(1, 5)}.jpeg",
"Baked Potato": f"/assets/menu_item_images/sides/baked_potato/img_{randint(1, 5)}.jpeg",
"Creamed Spinach": f"/assets/menu_item_images/sides/creamed_spinach/img_{randint(1, 5)}.jpeg",
"Garden Salad": f"/assets/menu_item_images/sides/garden_salad/img_{randint(1, 5)}.jpeg",
"Mac and Cheese": f"/assets/menu_item_images/sides/mac_and_cheese/img_{randint(1, 5)}.jpeg",
"Onion Rings": f"/assets/menu_item_images/sides/onion_rings/img_{randint(1, 5)}.jpeg",
"Tater Tots": f"/assets/menu_item_images/sides/tater_tots/img_{randint(1, 5)}.jpeg",
"Breadsticks": f"/assets/menu_item_images/sides/breadsticks/img_{randint(1, 5)}.jpeg",
"Edemame": f"/assets/menu_item_images/sides/edemame/img_{randint(1, 5)}.jpeg",
"Garlic Bread": f"/assets/menu_item_images/sides/garlic_bread/img_{randint(1, 5)}.jpeg",
"Mashed_Potatoes": f"/assets/menu_item_images/sides/mashed_potatoes/img_{randint(1, 5)}.jpeg",
"Roasted Cauliflower": f"/assets/menu_item_images/sides/roasted_cauliflower/img_{randint(1, 5)}.jpeg"
}
